//project types 
export const ADD_PROJECTS = "ADD_PROJECTS"; 
export const PROJECTS_LOADING = "PROJECTS_LOADING"; 
export const PROJECTS_FAILED = "PROJECTS_FAILED"; 
export const UPDATE_PROJECT = "UPDATE_PROJECT"; 
export const CREATE_PROJECT = "CREATE_PROJECT"; 
//phase types 
export const ADD_PHASES = "ADD_PHASES"; 
export const PHASES_LOADING = "PHASES_LOADING"; 
export const PHASES_FAILED = "PHASES_FAILED"; 
export const UPDATE_PHASE = "UPDATE_PHASE";
export const CREATE_PHASE = "CREATE_PHASE"; 
//log types 
export const ADD_LOG = "ADD_LOG"; 
export const LOG_LOADING = "LOG_LOADING"; 
export const LOG_FAILED = "PROJECTS_FAILED"; 
export const CREATE_LOG_ENTRY = "CREATE_LOG_ENTRY";  
//UI types 
export const DETAILS_OPEN = "DETAILS_OPEN"; 
export const INITIALIZE_UI = "INITIALIZE_UI";
export const DETAILS_CLOSE = "DETAILS_CLOSE";
export const PHASE_UPDATE_MODAL_OPEN = "PHASE_MODAL_OPEN";
export const PHASE_UPDATE_MODAL_CLOSE = "PHASE_MODAL_CLOSE";  
export const PROJECT_UPDATE_MODAL_OPEN = "PROJECT_MODAL_OPEN";  
export const PROJECT_UPDATE_MODAL_CLOSE = "PROJECT_MODAL_CLOSE"; 
export const PROJECT_CREATE_MODAL_OPEN = "PROJECT_CREATE_MODAL_OPEN";
export const PROJECT_CREATE_MODAL_CLOSE = "PROJECT_CREATE_MODAL_CLOSE";
export const PHASE_CREATE_MODAL_OPEN = "PHASE_CREATE_MODAL_OPEN";  
export const PHASE_CREATE_MODAL_CLOSE = "PHASE_CREATE_MODAL_CLOSE";    